# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.srcs/sources_1/ip/my_img_data/my_img_data.xci
# IP: The module: 'my_img_data' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.srcs/sources_1/ip/my_img_data/my_img_data_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_img_data'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.srcs/sources_1/ip/my_img_data/my_img_data.xci
# IP: The module: 'my_img_data' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.srcs/sources_1/ip/my_img_data/my_img_data_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_img_data'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
