# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.cache/wt [current_project]
set_property parent.project_path C:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths c:/AVNET_ZED_HDMI/2014_1/avnet_zed_hdmi_core [current_project]
set_property ip_output_repo c:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet c:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.srcs/sources_1/ip/my_img_data/my_img_data.xci
set_property used_in_implementation false [get_files -all c:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.srcs/sources_1/ip/my_img_data/my_img_data_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

set cached_ip [config_ip_cache -export -no_bom -use_project_ipc -dir C:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.runs/my_img_data_synth_1 -new_name my_img_data -ip [get_ips my_img_data]]

if { $cached_ip eq {} } {

synth_design -top my_img_data -part xc7z020clg484-1 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
# disable binary constraint mode for IPCache checkpoints
set_param constraints.enableBinaryConstraints false

catch {
 write_checkpoint -force -noxdef -rename_prefix my_img_data_ my_img_data.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ my_img_data_stub.v
 lappend ipCachedFiles my_img_data_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ my_img_data_stub.vhdl
 lappend ipCachedFiles my_img_data_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ my_img_data_sim_netlist.v
 lappend ipCachedFiles my_img_data_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ my_img_data_sim_netlist.vhdl
 lappend ipCachedFiles my_img_data_sim_netlist.vhdl

 config_ip_cache -add -dcp my_img_data.dcp -move_files $ipCachedFiles -use_project_ipc -ip [get_ips my_img_data]
}

rename_ref -prefix_all my_img_data_

# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef my_img_data.dcp
create_report "my_img_data_synth_1_synth_report_utilization_0" "report_utilization -file my_img_data_utilization_synth.rpt -pb my_img_data_utilization_synth.pb"

if { [catch {
  file copy -force C:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.runs/my_img_data_synth_1/my_img_data.dcp c:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.srcs/sources_1/ip/my_img_data/my_img_data.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub c:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.srcs/sources_1/ip/my_img_data/my_img_data_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub c:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.srcs/sources_1/ip/my_img_data/my_img_data_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim c:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.srcs/sources_1/ip/my_img_data/my_img_data_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim c:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.srcs/sources_1/ip/my_img_data/my_img_data_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force C:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.runs/my_img_data_synth_1/my_img_data.dcp c:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.srcs/sources_1/ip/my_img_data/my_img_data.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force C:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.runs/my_img_data_synth_1/my_img_data_stub.v c:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.srcs/sources_1/ip/my_img_data/my_img_data_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.runs/my_img_data_synth_1/my_img_data_stub.vhdl c:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.srcs/sources_1/ip/my_img_data/my_img_data_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.runs/my_img_data_synth_1/my_img_data_sim_netlist.v c:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.srcs/sources_1/ip/my_img_data/my_img_data_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.runs/my_img_data_synth_1/my_img_data_sim_netlist.vhdl c:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.srcs/sources_1/ip/my_img_data/my_img_data_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir C:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.ip_user_files/ip/my_img_data]} {
  catch { 
    file copy -force c:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.srcs/sources_1/ip/my_img_data/my_img_data_stub.v C:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.ip_user_files/ip/my_img_data
  }
}

if {[file isdir C:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.ip_user_files/ip/my_img_data]} {
  catch { 
    file copy -force c:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.srcs/sources_1/ip/my_img_data/my_img_data_stub.vhdl C:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.ip_user_files/ip/my_img_data
  }
}
