# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.cache/wt [current_project]
set_property parent.project_path C:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths c:/AVNET_ZED_HDMI/2014_1/avnet_zed_hdmi_core [current_project]
set_property ip_output_repo c:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Zynq_Book/Zynq_Mandel/Coor_gen.v
  C:/Zynq_Book/Zynq_Mandel/Engine.v
  C:/Zynq_Book/Zynq_Mandel/Engine2VGA.v
  C:/Zynq_Book/Zynq_Mandel/Mod_counter.v
  C:/Zynq_Book/Zynq_Mandel/VGA.v
  C:/Zynq_Book/Zynq_Mandel/VGA_Controller.v
  C:/Zynq_Book/Zynq_Mandel/Mandel.v
}
read_ip -quiet c:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.srcs/sources_1/ip/engine_pll/engine_pll.xci
set_property used_in_implementation false [get_files -all c:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.srcs/sources_1/ip/engine_pll/engine_pll_board.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.srcs/sources_1/ip/engine_pll/engine_pll.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.srcs/sources_1/ip/engine_pll/engine_pll_ooc.xdc]

read_ip -quiet c:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.srcs/sources_1/ip/my_img_data/my_img_data.xci
set_property used_in_implementation false [get_files -all c:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.srcs/sources_1/ip/my_img_data/my_img_data_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Zynq_Book/Zynq_Mandel/zedboard_constraints.xdc
set_property used_in_implementation false [get_files C:/Zynq_Book/Zynq_Mandel/zedboard_constraints.xdc]


synth_design -top Mandel -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Mandel.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Mandel_utilization_synth.rpt -pb Mandel_utilization_synth.pb"
