# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.srcs/sources_1/ip/engine_pll/engine_pll.xci
# IP: The module: 'engine_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.srcs/sources_1/ip/engine_pll/engine_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'engine_pll'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.srcs/sources_1/ip/engine_pll/engine_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'engine_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.srcs/sources_1/ip/engine_pll/engine_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'engine_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.srcs/sources_1/ip/engine_pll/engine_pll.xci
# IP: The module: 'engine_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.srcs/sources_1/ip/engine_pll/engine_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'engine_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.srcs/sources_1/ip/engine_pll/engine_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'engine_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Zynq_Book/Zedboard_Mandel/Zedboard_Mandel.srcs/sources_1/ip/engine_pll/engine_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'engine_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
